[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day_1 = "F9t1oQCP1Qtxpg5vBArTMHexnM8H6pusJ5D5wzBoX6qj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/ajackti/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
