[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day_21 = "Hv886856E859RWQTVb5C5usTEseCjL4mnVY4Zz5D2jiy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/ajackti/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
