[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day_24 = "3AYs54P3hR8QhZJZ8fx5VgtB9swgczQk1qMt3F4HH68a"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/ajackti/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
