[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
storage_int = "539akdBP7FAcZyT6mc4wig1z45GCMPgo7vLrUNR31Fpf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/ajackti/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
