[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day_11 = "AfZPmgAmqmmzU7swsVdgaF1QD1gGL2jqJyvFGAwxULf2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/ajackti/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
